apiVersion: apps/v1
kind: Deployment
metadata:
  name: jinja-render
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jinja-render
  template:
    metadata:
      labels:
        app: jinja-render
    spec:
      containers:
        - name: jinja-render
          image: muzammilpeer/jinja-render:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: jinja-render-service
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30082
  selector:
    app: jinja-render
