apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jinja-render-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jinja-render
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
